package pkg

import (
	"crypto/ecdsa"
	"crypto/elliptic"
	"crypto/rand"
	"encoding/base64"
	"encoding/hex"
	"fmt"
	"path/filepath"
	"strings"
)

// EnvFileName is the dotenv file generated by `liorian init` from a template
// sample.
const EnvFileName = ".env"

// EnvSampleCandidates lists the template file names probed as the source of the
// generated .env, in order of preference. The first existing file wins.
var EnvSampleCandidates = []string{
	".env-sample",
	".env.sample",
	".env.example",
	".env.dist",
	".env.template",
}

// FindEnvSample returns the path of the first .env sample found in dir, or an
// empty string when the directory ships none.
func FindEnvSample(dir string) string {
	for _, name := range EnvSampleCandidates {
		path := filepath.Join(dir, name)
		if FileExists(path) {
			return path
		}
	}
	return ""
}

// EnvLine is one line of a dotenv file. Comment and blank lines keep their
// original raw text (Key is empty); variable lines expose their Key and Value
// without the surrounding quotes.
type EnvLine struct {
	Raw   string
	Key   string
	Value string
	quote byte
}

// EnvFile is a parsed dotenv file that preserves comments, blank lines and
// variable order so a generated .env stays as close as possible to its sample.
type EnvFile struct {
	lines []EnvLine
}

// ParseEnv parses dotenv content, keeping comments and blank lines. CRLF line
// endings are normalised to LF.
func ParseEnv(data []byte) *EnvFile {
	text := strings.ReplaceAll(string(data), "\r\n", "\n")
	f := &EnvFile{}
	for _, raw := range strings.Split(text, "\n") {
		f.lines = append(f.lines, parseEnvLine(raw))
	}
	return f
}

// parseEnvLine splits a single dotenv line into its key/value pair. Lines that
// are not variable assignments are kept verbatim.
func parseEnvLine(raw string) EnvLine {
	trimmed := strings.TrimSpace(raw)
	if trimmed == "" || strings.HasPrefix(trimmed, "#") {
		return EnvLine{Raw: raw}
	}
	body := trimmed
	if rest, ok := strings.CutPrefix(body, "export "); ok {
		body = strings.TrimSpace(rest)
	}
	eq := strings.IndexByte(body, '=')
	if eq <= 0 {
		return EnvLine{Raw: raw}
	}
	key := strings.TrimSpace(body[:eq])
	value := strings.TrimSpace(body[eq+1:])
	var quote byte
	if len(value) >= 2 {
		first, last := value[0], value[len(value)-1]
		if (first == '"' || first == '\'') && last == first {
			quote, value = first, value[1:len(value)-1]
		}
	}
	return EnvLine{Key: key, Value: value, quote: quote}
}

// Keys returns the variable names in file order.
func (f *EnvFile) Keys() []string {
	keys := make([]string, 0, len(f.lines))
	for _, l := range f.lines {
		if l.Key != "" {
			keys = append(keys, l.Key)
		}
	}
	return keys
}

// Get returns the value of key and whether the variable is defined.
func (f *EnvFile) Get(key string) (string, bool) {
	for _, l := range f.lines {
		if l.Key == key {
			return l.Value, true
		}
	}
	return "", false
}

// Set updates the value of key, preserving its quote style, or appends the
// variable when it is missing.
func (f *EnvFile) Set(key, value string) {
	for i := range f.lines {
		if f.lines[i].Key == key {
			f.lines[i].Value = value
			return
		}
	}
	f.lines = append(f.lines, EnvLine{Key: key, Value: value})
}

// Render serialises the env file back to dotenv syntax.
func (f *EnvFile) Render() string {
	out := make([]string, 0, len(f.lines))
	for _, l := range f.lines {
		if l.Key == "" {
			out = append(out, l.Raw)
			continue
		}
		out = append(out, l.Key+"="+formatEnvValue(l.Value, l.quote))
	}
	return strings.Join(out, "\n")
}

// formatEnvValue renders a value, honouring an existing quote style and adding
// double quotes when the raw value would otherwise be ambiguous.
func formatEnvValue(value string, quote byte) string {
	if quote == '"' || quote == '\'' {
		return string(quote) + strings.ReplaceAll(value, string(quote), `\`+string(quote)) + string(quote)
	}
	if value == "" || strings.ContainsAny(value, " \t#'\"") {
		return `"` + strings.ReplaceAll(value, `"`, `\"`) + `"`
	}
	return value
}

// NewEncryptionKey returns a 32-byte random key hex-encoded (64 characters),
// suitable for a symmetric application key such as NEXT_PUBLIC_ENCRYPTION_KEY.
func NewEncryptionKey() (string, error) {
	key, err := NewRandomKey()
	if err != nil {
		return "", err
	}
	return hex.EncodeToString(key), nil
}

// NewVAPIDKeys generates a VAPID key pair (ECDSA P-256) for Web Push. Both keys
// are base64url-encoded without padding: the public key is the uncompressed
// elliptic point (65 bytes) and the private key the 32-byte scalar, matching
// the format produced by `web-push generate-vapid-keys`.
func NewVAPIDKeys() (publicKey, privateKey string, err error) {
	priv, err := ecdsa.GenerateKey(elliptic.P256(), rand.Reader)
	if err != nil {
		return "", "", fmt.Errorf("failed to generate the VAPID key pair: %w", err)
	}
	pub := elliptic.Marshal(elliptic.P256(), priv.PublicKey.X, priv.PublicKey.Y)
	scalar := priv.D.FillBytes(make([]byte, 32))
	return base64.RawURLEncoding.EncodeToString(pub), base64.RawURLEncoding.EncodeToString(scalar), nil
}
